spring:
  r2dbc: # (1)
    url: ${gcp.cloudsql.url}
    username: ${gcp.cloudsql.username}
    password: ${gcp.cloudsql.password}

  application:
    name: main

  cloud:
    gcp:
      storage:
        project-id: {gcp.project.id}
        credentials:
          location: {gcp.key.path}
        bucket: {gcp.bucket}
        max-size: 5242880


server:
  port: 8081

springdoc:
  swagger-ui:
    path : /swagger
    tags-sorter : alpha
    operations-sorter : alpha
  api-docs.path : /api-docs
  default-consumes-media-type : application/json;charset=UTF-8
  default-produces-media-type : application/json;charset=UTF-8


social:
  kakao:
    url: "https://kapi.kakao.com/v2/user/me"

security:
  swagger:
    user: ${swagger.user}
    password: ${swagger.password}
  bearerAuth: []

jwt:
  secret: ${jwt.secret}
  access-expire: ${jwt.access-expire}
  refresh-expire: ${jwt.refresh-expire}
