spring:
  r2dbc: # (1)
    url: r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:       # (2)
  console:
    port: 8090
  application:
    name: main

server:
  port: 8081

springdoc:
  swagger-ui:
    path : /swagger
    tags-sorter : alpha
    operations-sorter : alpha
  api-docs.path : /api-docs
  default-consumes-media-type : application/json;charset=UTF-8
  default-produces-media-type : application/json;charset=UTF-8
