spring:
  r2dbc: # (1)
    url: r2dbc:pool:postgresql://localhost:5432/test
    username: test
    password: test
  security:
    debug: true

  application:
    name: main
  cloud:
    gcp:
      storage:
        project-id:
        credentials:
          location:
        bucket:
        max-size: 5242880


server:
  port: 8081

springdoc:
  swagger-ui:
    path : /swagger
    tags-sorter : alpha
    operations-sorter : alpha
  api-docs.path : /api-docs
  default-consumes-media-type : application/json;charset=UTF-8
  default-produces-media-type : application/json;charset=UTF-8


social:
  kakao:
    url: "https://kapi.kakao.com/v2/user/me"

security:
  swagger:
    user: admin
    password: test
  bearerAuth: []

jwt:
  secret: "snapfitjwttactbefefefefeftateotbtotbse"
  access-expire: 1000
  refresh-expire: 10000


logging:
  level:
    org.springframework.r2dbc.core: debug
    org:
      springframework:
        security: DEBUG
